<?xml version="1.0" encoding="utf-8"?><Database Name="DSDBDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-537UFSSA\SQLEXPRESS;Initial Catalog=DSDBDatabase;Integrated Security=True;Pooling=False" SettingsObjectName="DigitalSafetyDepositBoxClass.Properties.Settings" SettingsPropertyName="DSDBDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="password_salt" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="user_name_is_email" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="void_ind" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="USER_FILE" Member="FILEs" ThisKey="user_id" OtherKey="user_id" Type="FILE" />
    </Type>
  </Table>
  <Table Name="dbo.FILES" Member="FILEs">
    <Type Name="FILE">
      <Column Name="file_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="file_name" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="file_contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="type" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="container_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="void_int" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="USER_FILE" Member="USER" ThisKey="user_id" OtherKey="user_id" Type="USER" IsForeignKey="true" />
    </Type>
  </Table>
</Database>